import type { Metadata } from "next";
import { aeonikVariables } from "./fonts/aeonik";
import { chillaxVariables } from "./fonts/chillax";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ray Chu - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${chillaxVariables} ${aeonikVariables}`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
